# Generated by Django 5.2.5 on 2025-08-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldata',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
